# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 17cb3027eb1643dc8147aeb92e56ea1d66dfaa296aa22bfe68ce992f5098dbd5965386456149aeab6c484ab570a5f2680370c0086544e028c169a0b33a6ae77b

test:
  secret_key_base: 1a0f2321cad2628d51a36763c00534c13c717b61a73839ee5ded26c16464f9a481200f60375be8f42b790feb9b0d7e0357f84460ed8c1a7fab201c34181db859

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
